# Generated by Django 4.2 on 2023-04-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Rating'),
        ),
    ]
