# Generated by Django 4.2 on 2023-04-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_contactuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Image'),
        ),
    ]
