# Generated by Django 4.2 on 2023-04-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='svg',
            field=models.FileField(null=True, upload_to='category/', verbose_name='Image_svg'),
        ),
    ]
