# Generated by Django 4.2 on 2023-04-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_category_image_category_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuser',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contacts_file/', verbose_name='File'),
        ),
    ]
