# Generated by Django 4.2 on 2023-04-11 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_contactuser_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='depth',
            field=models.FloatField(default=0, verbose_name='Depth'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.FloatField(default=0, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.FloatField(default=0, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='Product'),
        ),
    ]
