# Generated by Django 4.2 on 2023-04-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_depth_product_height_product_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to='category/', verbose_name='Image_svg'),
        ),
    ]
