# Generated by Django 4.2 on 2023-04-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_category_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='svg_mobile',
            field=models.FileField(blank=True, null=True, upload_to='category/mobile_svg', verbose_name='Image mobile svg'),
        ),
        migrations.AlterField(
            model_name='category',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to='category/', verbose_name='Image svg'),
        ),
    ]
