# Generated by Django 4.2 on 2023-04-13 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_category_svg_mobile_alter_category_svg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discreption',
            new_name='description',
        ),
    ]
