# Generated by Django 4.2 on 2023-04-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_discreption_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=255, verbose_name='Цвет')),
                ('color_code', models.CharField(max_length=255, verbose_name='Код цвета')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
    ]
