# Generated by Django 4.2 on 2023-04-19 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_availablecolors'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablecolors',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
    ]
