# Generated by Django 4.2 on 2023-04-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_availablecolors_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablecolors',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
    ]
