# Generated by Django 4.2 on 2023-04-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_alter_contactuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='color_title',
            field=models.CharField(default=1, max_length=255, verbose_name='Цвет'),
            preserve_default=False,
        ),
    ]
