# Generated by Django 4.2 on 2023-04-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_shippingaddress_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=9001322299, verbose_name='ID'),
        ),
    ]
