# Generated by Django 4.2 on 2023-04-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
