# Generated by Django 4.2 on 2023-04-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='apartment_number',
            field=models.IntegerField(default=1, verbose_name='Номер аппартамента'),
            preserve_default=False,
        ),
    ]
