# Generated by Django 4.2 on 2023-04-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_order_apartment_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='apartment_number',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='apartment_number',
            field=models.IntegerField(default=1, verbose_name='Номер аппартамента'),
            preserve_default=False,
        ),
    ]
