# Generated by Django 4.2 on 2023-04-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_historyproducts_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Цена'),
        ),
    ]
