# Generated by Django 4.2 on 2023-04-26 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0029_alter_shippingaddress_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddressPermanent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адресс доставки')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment_number', models.IntegerField(verbose_name='Номер аппартамента')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.city', verbose_name='Город доставки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Адрес постоянной доставки',
                'verbose_name_plural': 'Адрес постоянных доставок',
            },
        ),
    ]
